src/Plug.vala

Make sure we reload info when we create the location manager

---

src/Widgets/LocaleSetting.vala

Check for existence of the gweather schema and show unit settings if it exists

Temp units

---

src/Widgets/LocaleSetting.vala

* Code style
* Copyright header
* GObject-style construction
* Use a class for EndLabel instead of a method
* `column_homogeneous` instead of magic number size requests
* correct margins
* Grid instead of box
* cuddle else

LocaleSetting.vala: GObject-style

---

src/Widgets/InstallPopover.vala

* GObject-style construction
* Reduce variable scope
* Update copyright
* Grid not box

InstallPopover.vala: minor cleanups

---

src/Widgets/LanguageListBox.vala

* Brackets on if/else
* GObject-style
* Grid instead of box
* Update copyright header

Make LanguageRow use GObject-style construction

---

src/Plug.vala
src/Widgets/InstallInfoBar.vala

* Use construct
* Use properties instead of set methods
* Update copyright
* Remove unused variables

Rewrite InstallInfoBar.vala

---

src/Widgets/LocaleView.vala

* GObject-style
* Code style
* Grid instead of Box
* ActionBar and buttons instead of Toolbar and ToolButton
* Catch GLib error
* Reduce variable scope

Rewrite LocaleView.vala

---

src/Widgets/LocaleSetting.vala
src/Widgets/Preview.vala

* GObject-style
* Use grid instead of a single label for even spacing with arbitrary formats
* Margins in LocaleSetting.vala instead of internal to this widget
* Remove unused LocaleManager
* Don't set sensitive for legibility
Before:
After:

Preview.vala: rewrite

---

src/Installer/UbuntuInstaller.vala
src/Plug.vala
src/Utils.vala
src/Widgets/LocaleSetting.vala

* Refactor Utils.vala
* Cache the results of executing commands
* Make loading languages happen in a separate thread so the animation to the plug doesn't stutter like crazy

Make loading languages happen in a separate thread and async

---

src/LocaleManager.vala
src/Plug.vala

* Remove unneded and not working `connected` signal
* Use `unowned` for unowned variables
* Put more complex lambdas into their own callbacks
* Cache some variables for later use

Refactor Plug.vala

---

src/Plug.vala

Move utils initialization to get_widget

---

src/Plug.vala

Make things simple on ourselves and just declare the grid orientation as vertical and add

Plug.vala: use a vertical grid with add

---

debian/control

Depend on aptdaemon

---

src/Widgets/LocaleSetting.vala
src/Widgets/LocaleView.vala

Also do some small cleanups and move in the keyboard settings button

Use Granite.SimpleSettingsPage

---

src/Installer/aptd-client.vala
src/LocaleManager.vala

Fix warnings about IOError by using GLib.Error instead.
Also fix a bunch of brackets and spaces while we're here touching stuff

Change IOError to GLib.Error

---

src/Widgets/LocaleSetting.vala

Hide Regions Combobox if there is no region available

---

src/Widgets/LocaleSetting.vala

Sort Region and Format list

---

src/Widgets/InstallPopover.vala

InstallPopover: design refresh

---

src/Plug.vala
src/Utils.vala
src/Widgets/InstallPopover.vala
src/Widgets/LocaleSetting.vala
src/Widgets/LocaleView.vala

Instead of making the user authenticate ahead of time in the infobar, ask for permission when it's needed
Fixes #43

Ask for Permission

---

src/Plug.vala
src/Widgets/LocaleView.vala

Animate the login/logout warning!

Plug.vala: Animate infobar hide/show for login/logout warning

---

src/Installer/UbuntuInstaller.vala

* Put the namespace in the class name
* Add a new line after closing brackets when there's no another closing bracket or else
* Use brackets even if there's only one line in the `if` statement
* No new line at the beginning and end of functions
* Remove unused constants
* Clarify private access modifiers
* Less scope
Review in no whitespace changes mode.
Edit: Too much changes? :thinking:

UbuntuInstaller: Code cleanup

---

src/Installer/aptd-client.vala

* Use 4 spaces instead of 2
* Instance members at the top
* Have a space before a colon

aptd-client: Update code style

---

data/io.elementary.switchboard.locale.appdata.xml.in

For better display in Feedback and AppCenter

AppData: Locale → Language & Region Settings

---

data/io.elementary.switchboard.locale.appdata.xml.in
meson.build

Release 2.5.3

---

config.vala.in
meson.build
src/Plug.vala

Provides the directory where the locales are actually installed.

l10n: Correctly setup the locales

---

.github/workflows/Release.yml

Reverts elementary/switchboard-plug-locale#152

Revert "Update Release.yml"

---

data/io.elementary.switchboard.locale.appdata.xml.in

To cover the change introduced in #158

appdata: Update for recent changes

---

meson.build

Only very minimal code changes here, but potentially very useful for people with 3-letter language codes or people who want to use Central Kurdish as their system language.
AppData is up to date, may just want to wait a little while for some updated translations

Release 2.5.7

---

data/io.elementary.switchboard.locale.policy.in
data/meson.build

We are already embedding the translations.

policy: Do not specify the gettext-domain

---

src/Plug.vala

Remove unused variable

---

.github/workflows/main.yml
src/Widgets/LocaleSetting.vala

LocaleSetting: use Switchboard.SettingsPage

---

po/POTFILES
src/Widgets/InstallDialog.vala
src/Widgets/LocaleView.vala
src/meson.build

Use a modal dialog instead of a popover

InstallPopover → InstallDialog

---

src/ProgressDialog.vala
src/Widgets/InstallPopover.vala
src/Widgets/LocaleSetting.vala

Resolves deprecation warnings about Gtk.StyleContext

Use add_css_class

---

src/Widgets/LocaleView.vala

Matches pattern we've been following elsewhere

LocaleView: label in add button

---

src/Widgets/LocaleSetting.vala

Fixes #70 
And use expression instead of factory

LocaleSetting: add search to dropdowns

---

meson.build
src/Widgets/LanguageListBox.vala
src/Widgets/LocaleSetting.vala
src/Widgets/LocaleView.vala
src/meson.build

Add window controls to sidebar

---

data/locale.metainfo.xml.in
src/Widgets/LocaleSetting.vala

LocaleSetting: add option for auto temp unit

---

data/locale.metainfo.xml.in
src/Widgets/LanguageListBox.vala
src/Widgets/LocaleSetting.vala

Make items more screen reader accessible by setting description labels for added context

Add screen reader descriptions

---

debian/control

control: Require meson >= 0.58.0

---

src/Widgets/LocaleView.vala

Stores the sidebar position configured by the user.

Store Sidebar Position

---

src/Widgets/LanguageListBox.vala

Fixes https://github.com/elementary/switchboard-plug-locale/issues/221
Significantly speeds up loading the plug

Use check button for selected check
