src/Installer/UbuntuInstaller.vala
See comment to #39 (Complete install does not work)
=> Use instance variable missing_languages not local.

src/Plug.vala
Fixes button alignment by using native infobar features correctly
=> Fix button alignment in install missing infobar

src/Utils.vala
Add a null check when restoring the envvar. If the `LANGUAGE` environment variable wasn't set in the first place, we end up stuck with the language set to whatever language was used to translate the string in this method.
Will fix https://github.com/elementary/os/issues/56
=> Prevent overwriting of LANGUAGE envvar if not set

src/Utils.vala
It's possible to have locales that are more than 5 characters long, example: https://lh.2xlibre.net/locale/unm_US/
=> Don't hardcode locale name length

src/Plug.vala
I don't see where these are used in this code :man_shrugging:
=> Plug: Remove unused constants

src/Plug.vala
Animate the missing languages infobar!
=> Plug.vala: Animate infobar hide/show for missing languages

src/Installer/UbuntuInstaller.vala, src/Installer/aptd-client.vala, src/LocaleManager.vala, src/Plug.vala, src/Widgets/InstallPopover.vala
This fixes linting errors in the src directory.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d src
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint -d src
```
=> lint src directory files via vala-lint

src/Installer/UbuntuInstaller.vala, src/Plug.vala, src/Utils.vala, src/Widgets/LanguageListBox.vala
Fixes #102
Supersedes #103
* Remove an unnecessary space from transaction_id (its format was `"r-" + <language code>` for removal, but `"i- " + <language code>` for installation, which causes wrong langcode output)
* Use `Gee.ArrayList` instead of `string[]` (because the latter does not seem to support removing elements?)
* Add/remove the designated language to/from the languages list on adding/removing the language
=> Update the languages list on adding/removing a language

src/Plug.vala, src/Widgets/LocaleView.vala
Because the `on_install_language` method is accessed only from the `language_selected` signal of the popover in LocaleView.vala and considering unifying the code format to the signal of remove_button above the `language_selected` signal, I personally think this makes more sense.
=> Make the installation trigger code more readable

src/Installer/UbuntuInstaller.vala, src/Plug.vala, src/ProgressDialog.vala, src/Widgets/LocaleView.vala
This will enable us to stop passing around signals in future branches, since we need access to this from a couple different places
=> Make UbuntuInstaller a singleton

src/Installer/UbuntuInstaller.vala
Fixes the following warning is shown when installing/removing a language:
```
(io.elementary.switchboard:8612): GLib-GObject-WARNING **: 16:07:38.596: ../../../../gobject/gbinding.c:857: The source object of type SwitchboardPlugLocaleInstallerUbuntuInstaller has no property called 'install-cancellable'
```
=> Fix the property 'install-cancellable' warning

src/Widgets/LocaleSetting.vala
The docs on SettingsSchemaSource get_default say
```
The returned source may actually consist of multiple schema sources from different directories, depending on which directories were given in `XDG_DATA_DIRS` and `GSETTINGS_SCHEMA_DIR`. For this reason, all lookups performed against the default source should probably be done recursively.
```
Without this in NixOS it will not work as intended, as we
have multiple entries in XDG_DATA_DIRS.
=> LocaleSetting: lookup schemas recursive

src/ProgressDialog.vala
=> ProgressDialog: Set 'resizable' to false

src/Utils.vala, src/Widgets/LanguageListBox.vala
`language-options` is an Ubuntu-specific perl script installed as an extension to AccountsService.
`libgnome-desktop` provides `Gnome.Languages.get_all_locales` that achieves the same thing in a way that will work on other distros.
I've also removed the hardcoded length checks on the locales as this would have been preventing some of the 3 letter locales from being parsed and displayed. There's a GNOME method that can do that parsing for us.
There's a bunch of other Ubuntu specific stuff in this plug, but I'll make changes in small increments like this so we can test it a bit a time. This changes how the lists of available languages and regions are loaded. On Odin, this has no effect on the top level list of "installed languages", but there seem to be more regions available with this …
=> Utils: Replace usage of language-options

src/LocaleManager.vala, src/Utils.vala, src/Widgets/LocaleSetting.vala, src/Widgets/LocaleView.vala
Fixes #143 
In many cases we were assembling the locale string to set on the user in accounts service manually. For example, we would get the language code (e.g. `en`) and the region code (e.g. `US`) and assemble them together into `en_US`, in some cases checking that they were exactly 2 characters long. There are some codes that are 3 letters, so this would have caused issues with those locales.
More problematic is that setting `en_US` or `de_DE` as a user's AccountsService language on Fedora causes rather big issues with localisation as the AccountsService documentation states it expects the setting to include the codepage (i.e. `de_DE.UTF-8`). I believe that the Ubuntu version of AccountsService has been patched in some way to prevent those issues from occuring here.
Either way, it's …
=> Set locale including codeset

src/Plug.vala, src/Utils.vala, src/Widgets/LocaleSetting.vala
We don't need to run `locale -a`, filter it down the `utf8` formats, then manually replace and add `.UTF-8` onto them when libgnome-desktop already provides the locales in the right format for us.
To test:
* Check the "Formats" dropdown still contains a sensible list of locales we can set the formats from
=> Get available formats from libgnome-desktop

data/io.elementary.switchboard.locale.appdata.xml.in, src/LocaleManager.vala, src/Plug.vala, src/Widgets/LocaleSetting.vala
I've broken out part of #147 for this
Fixes #83 
**In `LocaleManager.vala`:**
Make sure we fall back to our alternative ways of getting the user's formats if its not set on AccountsService.
**In `Plug.vala`:**
Since the `langs` array is overwritten by the `reload` method, it doesn't make sense to add/remove stuff first.
**In `LocaleSetting.vala`:**
Since the tree store is sorted alphabetically on the human readable name of the language (which could be translated), it doesn't make sense to try and select the active one by index, because the indexes could change on sort. So we use the locale key to select the active entry.
=> Select correct format after install/remove

data/languagelist
Fixes #157 
Note that this is enough to get the language to show, but it will not be usable until #156 is also merged.
=> languagelist: Add Kurdish, Central

data/io.elementary.switchboard.locale.appdata.xml.in, src/Installer/UbuntuInstaller.vala
We cannot assume that language codes will be 2 characters long. This prevents the installation and removal of languages that have 3 letter codes and/or additional variants.
To test:
* With master, try installing the "Tatar, Crimean" (`crh`) language.
* Note that no progress indicator appears, and the language is not available after "installation". There is another bug that prevents the list updating after changes (#149), but even after a restart of the plug, "Tatar, Crimean" will not be available.
* Install this branch and try again.
* Note that the progress window does indeed appear this time
* After a restart of the plug, the language should be available.
=> installer: Don't trim language codes

po/extra/POTFILES
Fixes the Gettext Actions [failing](https://github.com/elementary/switchboard-plug-locale/runs/6284028893?check_suite_focus=true) in the latest master branch.
=> POTFILES: Update the suffix of the policy file

src/Plug.vala, src/Widgets/LocaleSetting.vala, src/Widgets/LocaleView.vala
Trying to get infobars off the top of the screen since window controls will be in the page header
=> LocaleSetting: absorb restart infobar

src/Widgets/LocaleView.vala
We already throw modal progress dialogs during a transaction so I don't see why we need this?
=> LocaleView: remove make_sensitive

src/Plug.vala, src/Widgets/LocaleSetting.vala
=> LocaleSettings: absorb missing_lang_infobar

src/Installer/UbuntuInstaller.vala
Fixes #200 
A simplistic fix for the linked issue.  It might result in uninstalled and unwanted font packages but this is the lesser evil if no better solution can be found.
An alternative would be to add specific multilanguage fonts to the list of excluded packages for uninstalling but I am not sure what a complete list would be.
=> Do not uninstall font packages with language

src/Widgets/LocaleSetting.vala
Setting path changed in OS 8. Is it worth supporting both?
=> LocaleSetting: support GWeather4

src/Widgets/LocaleSetting.vala
* Makes it more explicit why you would want to go to keyboard settings
* I'm also seeing some confusion about date and time settings not being set by region setting as in #173, so make it explicit that Date & Time is its own settings section by linking to it
=> LocaleSetting: show links inline

src/Plug.vala, src/Widgets/LocaleView.vala
* Removes some public API
* Fix implicit begin while we're here
=> LocaleView: absorb progressdialog

src/Widgets/LocaleView.vala
Fixes the following message is shown in the terminal when opening the plug:
```
** (io.elementary.settings:18513): CRITICAL **: 11:32:40.212: switchboard_plug_locale_installer_ubuntu_installer_check_missing_languages: assertion 'self != NULL' failed
```
This is because we're calling `installer.check_missing_languages ()` before initializing `installer` variable.
=> LocaleView: Fix access to UbuntuInstaller before initialization

data/packages_blocklist
Because we use IBus for a input method and want to prevent Fcitx things from being installed.
=> blocklist: Add fcitx5-frontend-qt6

src/Widgets/LanguageListBox.vala, src/Widgets/LocaleSetting.vala, src/Widgets/LocaleView.vala
Fixes #15
We set LANGUAGE environment variable and then call Gnome.Languages.get_language_from_locale or Gnome.Languages.get_country_from_code to get language and region names in their own languages.
However, we don't set LANGUAGE with both ISO 639 language code and ISO 3166 territory name (e.g. "ja_JP" or "zh_CN") here. Instead, we set it only with ISO 639 language code (e.g. "ja" or "zh").
Just setting language code doesn't work for some languages that has variants like Chinese and thus the Gnome.Languages APIs returns untranslated language names.
=> Fix some language and region names not shown in own languages

data/locale.metainfo.xml.in, src/Installer/UbuntuInstaller.vala, src/Utils.vala, src/Widgets/LocaleSetting.vala, src/Widgets/LocaleView.vala
=> UbuntuInstaller: get permission async

src/Widgets/LocaleSetting.vala, src/Widgets/Preview.vala
Many of the settings pages use a vertical layout. To maintain consistency across all settings, this view has also been updated.
- Info banners are now displayed at the top.
=> Vertical Design Update

src/Widgets/LocaleSetting.vala
These are related so put them in the same section. Very subtly less padding
=> LocaleSetting: pack region and formats in same box
